#--- The Kairo Project ----------------------------------------------------#
#                                                                          #
#   Part of the Kairo Project, under the Attribution 4.0 International     #
#   license (CC BY 4.0).  You are allowed to use, modify, redistribute,    #
#   and create derivative works, even for commercial purposes, provided    #
#   that you give appropriate credit, and indicate if changes were made.   #
#                                                                          #
#   For more information on the license terms and requirements, please     #
#     visit: https://creativecommons.org/licenses/by/4.0/                  #
#                                                                          #
#   SPDX-License-Identifier: Apache-2.0                                    #
#   Copyright (c) 2026 The Kairo Project (Apache-2.0)                      #
#                                                                          #
#------------------------------------------------------------ KAIRO -------#

[CL001]
brief = "place holder diagnostics"
group = "Uncategorized"
    [CL001.W]
    explain = "This is placeholder diagnostics. (Warning)"
    [CL001.I]
    explain = "This is placeholder diagnostics. (Info)"
    [CL001.R]
    explain = "This is placeholder diagnostics. (Remark)"
    [CL001.V]
    explain = "This is placeholder diagnostics. (Verbose)"
    [CL001.N]
    explain = "This is placeholder diagnostics. (Note)"
    [CL001.D]
    explain = "This is placeholder diagnostics. (Debug)"
    [CL001.E]
    explain = "This is placeholder diagnostics. (Error)"
    [CL001.F]
    explain = "This is placeholder diagnostics. (Fatal)"