[project]
name    = "Kairo"
version = "kairo-0.0.1+rc.20260220"
author  = "Dhruvan, Ojas and Arnav"
license = "CC-BY-4.0"

[workspace]
skip_dirs = ["build", "libs", "private"]

[build]
compiler = "kairo"
mode     = "release"

[[target]]
name            = "kairo"
entry           = "Toolchain/Driver/Main/kairo.kro"
type            = "binary"
includes        = ["Toolchain", "Lib/bootstrap/lib-helix"]
links           = []
libs            = []
deps            = []
defines         = ["VERSION=L\"kairo-0.1.1+rc.250306\""]
ld_flags        = []
cxx_sources     = []
cxx_passthrough = []

[[target]]
name     = "kbld"
entry    = "Toolchain/Driver/Main/kbld.kro"
type     = "binary"
includes = ["Toolchain"]
defines  = ["VERSION=L\"kbld-0.1.0+rc.250306\""]

[[target]]
name     = "kfmt"
entry    = "Toolchain/Driver/Main/kfmt.kro"
type     = "binary"
includes = ["Toolchain"]
defines  = ["VERSION=L\"kfmt-0.1.0+rc.250306\""]

[[target]]
name     = "kld"
entry    = "Toolchain/Driver/Main/kld.kro"
type     = "binary"
includes = ["Toolchain"]
defines  = ["VERSION=L\"kld-0.1.0+rc.250306\""]

[[target]]
name     = "klsp"
entry    = "Toolchain/Driver/Main/klsp.kro"
type     = "binary"
includes = ["Toolchain"]
defines  = ["VERSION=L\"klsp-0.1.0+rc.250306\""]

[[target]]
name     = "kpkg"
entry    = "Toolchain/Driver/Main/kpkg.kro"
type     = "binary"
includes = ["Toolchain"]
defines  = ["VERSION=L\"kpkg-0.1.0+rc.250306\""]
