[project]
name    = "Kairo"
version = "kairo-0.0.1+rc.20260220"
author  = "Dhruvan, Ojas and Arnav"
license = "CC-BY-4.0"

[workspace]
skip_dirs = ["build", "libs", "private"]

[build]
compiler = "kairo"
mode     = "release"

[[target]]
name     = "kairo"
entry    = "toolchain/Driver/main/kairo.kro"
type     = "binary"
includes = ["toolchain", "lib-helix/core"]
links    = []
libs     = []
deps     = []
defines  = []
ld_flags = []
cxx_sources    = []
cxx_passthrough = []

[[target]]
name     = "kbld"
entry    = "toolchain/Driver/main/kbld.kro"
type     = "binary"
includes = ["toolchain"]

[[target]]
name     = "kfmt"
entry    = "toolchain/Driver/main/kfmt.kro"
type     = "binary"
includes = ["toolchain"]

[[target]]
name     = "kld"
entry    = "toolchain/Driver/main/kld.kro"
type     = "binary"
includes = ["toolchain"]

[[target]]
name     = "klsp"
entry    = "toolchain/Driver/main/klsp.kro"
type     = "binary"
includes = ["toolchain"]

[[target]]
name     = "kpkg"
entry    = "toolchain/Driver/main/kpkg.kro"
type     = "binary"
includes = ["toolchain"]
