#--- The Kairo Project ----------------------------------------------------#
#                                                                          #
#   Part of the Kairo Project, under the Attribution 4.0 International     #
#   license (CC BY 4.0).  You are allowed to use, modify, redistribute,    #
#   and create derivative works, even for commercial purposes, provided    #
#   that you give appropriate credit, and indicate if changes were made.   #
#                                                                          #
#   For more information on the license terms and requirements, please     #
#     visit: https://creativecommons.org/licenses/by/4.0/                  #
#                                                                          #
#   SPDX-License-Identifier: CC-BY-4.0                                     #
#   Copyright (c) 2024 The Kairo Project (CC BY 4.0)                       #
#                                                                          #
#------------------------------------------------------------ KAIRO -------#

[I001]
brief = "place holder diagnostics"
group = "Uncategorized"
    [I001.W]
    explain = "This is placeholder diagnostics. (Warning)"
    [I001.I]
    explain = "This is placeholder diagnostics. (Info)"
    [I001.R]
    explain = "This is placeholder diagnostics. (Remark)"
    [I001.V]
    explain = "This is placeholder diagnostics. (Verbose)"
    [I001.N]
    explain = "This is placeholder diagnostics. (Note)"
    [I001.D]
    explain = "This is placeholder diagnostics. (Debug)"
    [I001.E]
    explain = "This is placeholder diagnostics. (Error)"
    [I001.F]
    explain = "This is placeholder diagnostics. (Fatal)"