#pragma once

#include "types.hpp"

namespace kbld {
inline auto generate_metadata(const ProjectConfig &proj,
                              const Target        &target,
                              const fs::path      &gen_dir) -> fs::path {
    fs::create_directories(gen_dir);

    auto timestamp = iso8601_now();

    if (is_windows()) {
        // Generate .rc file for Windows
        auto        rc_path    = gen_dir / (target.name + ".rc");
        std::string rc_content = fmt("#include <winver.h>\n"
                                     "\n"
                                     "VS_VERSION_INFO VERSIONINFO\n"
                                     "FILEVERSION 1,0,0,0\n"
                                     "PRODUCTVERSION 1,0,0,0\n"
                                     "BEGIN\n"
                                     "  BLOCK \"StringFileInfo\"\n"
                                     "  BEGIN\n"
                                     "    BLOCK \"040904E4\"\n"
                                     "    BEGIN\n"
                                     "      VALUE \"ProductName\", \"{}\"\n"
                                     "      VALUE \"ProductVersion\", \"{}\"\n"
                                     "      VALUE \"CompanyName\", \"{}\"\n"
                                     "      VALUE \"LegalCopyright\", \"{}\"\n"
                                     "      VALUE \"FileDescription\", \"{}\"\n"
                                     "    END\n"
                                     "  END\n"
                                     "  BLOCK \"VarFileInfo\"\n"
                                     "  BEGIN\n"
                                     "    VALUE \"Translation\", 0x0409, 1252\n"
                                     "  END\n"
                                     "END\n",
                                     proj.name,
                                     proj.version,
                                     proj.author,
                                     proj.license,
                                     target.name);
        write_file(rc_path, rc_content);
        return rc_path;
    }

    auto        cpp_path = gen_dir / (target.name + "_meta.cpp");
    std::string meta     = fmt("name={}|version={}|author={}|license={}|built={}",
                           proj.name,
                           proj.version,
                           proj.author,
                           proj.license,
                           timestamp);

    std::string cpp_content = fmt(
        "// Auto-generated by kbld — do not edit\n"
#if defined(__APPLE__)
        "__attribute__((section(\"__DATA,__build_meta\"), used))\n"
#else
        "__attribute__((section(\".build_meta\"), used))\n"
#endif
        "static const char kBuildMeta[] =\n"
        "    \"{}\";\n",
        meta
    );

    write_file(cpp_path, cpp_content);
    return cpp_path;
}

}  // namespace kbld
