# --- The Kairo Project -------------------------------------------------- #
#
#   Part of the Kairo Project, under the Apache License v2.0 with the
#   Kairo Runtime Library Exception.
#
#   See: https://www.kairolang.org/LICENSE.txt
#   SPDX-License-Identifier: Apache-2.0 WITH KAIRO-RUNTIME-EXCEPTION
#   Copyright (c) 2026 Dhruvan Kartik
#
# ------------------------------------------------------------------------ #

[L001]
brief = "place holder diagnostics"
group = "Uncategorized"
    [L001.W]
    explain = "This is placeholder diagnostics. (Warning)"
    [L001.I]
    explain = "This is placeholder diagnostics. (Info)"
    [L001.R]
    explain = "This is placeholder diagnostics. (Remark)"
    [L001.V]
    explain = "This is placeholder diagnostics. (Verbose)"
    [L001.N]
    explain = "This is placeholder diagnostics. (Note)"
    [L001.D]
    explain = "This is placeholder diagnostics. (Debug)"
    [L001.E]
    explain = "This is placeholder diagnostics. (Error)"
    [L001.F]
    explain = "This is placeholder diagnostics. (Fatal)"