// priv fn _is_assign_op(self, k: TokenKind) -> bool {
//     return (k == TokenKind::OpEqual)
//         || (k == TokenKind::OpPlusEqual)
//         || (k == TokenKind::OpMinusEqual)
//         || (k == TokenKind::OpStarEqual)
//         || (k == TokenKind::OpSlashEqual)
//         || (k == TokenKind::OpPercentEqual)
//         || (k == TokenKind::OpAmpEqual)
//         || (k == TokenKind::OpPipeEqual)
//         || (k == TokenKind::OpCaretEqual)
//         || (k == TokenKind::OpLessLessEqual)
//         || (k == TokenKind::OpGreaterGreaterEqual);
// }


a = 2
a = bin_ladin(10)

a = b = 5
alignof i32 = alignof i64 - alignof f80 = alignof f64
a = b - 8 = 5

a += 3
a + = 3
a=+3
