#!/usr/bin/env python3
"""
Reads diag.toml, generates DiagRegistry.kro
Usage: python3 gen_diag.py <folder with .diag.toml files> > DiagRegistry.kro
"""

import sys, tomllib, textwrap, os

CAT_MAP = {
    "S": "Syntax", "U": "Uncategorized", "C": "CodeGen",
    "M": "Memory", "R": "Resolution", "L": "Linker",
    "SC": "Semantic", "P": "Portability", "CL": "Lowering",
    "OPT": "Optimization", "I": "Internal",
}
SEV_MAP = {
    "I": "Ignored", "R": "Remark", "V": "Verbose",
    "N": "Note", "D": "Debug", "W": "Warning",
    "E": "Error", "F": "Fatal",
}

def parse_base_code(code: str):
    for prefix in sorted(CAT_MAP.keys(), key=len, reverse=True):
        if code.startswith(prefix):
            num = code[len(prefix):]
            return prefix, CAT_MAP[prefix], int(num)
    raise ValueError(f"bad code: {code}")

def main():
    if len(sys.argv) < 2:
        print(f"usage: {sys.argv[0]} <folder with .diag.toml files>", file=sys.stderr)
        sys.exit(1)

    # first we read all the toml files and merge them into a single string then parse it
    # get all the files in the folder that end with .diag.toml
    merged_toml = ""
    folder = sys.argv[1]
    toml_files = [sys.argv[1] + "/" + f for f in os.listdir(folder) if f.endswith(".diag.toml")]
    for toml_file in toml_files:
        with open(toml_file, "rb") as f:
            merged_toml += f.read().decode("utf-8") + "\n"
    
    
    
    # now parse the merged toml
    data = tomllib.loads(merged_toml)

    diags = []
    seen = set()

    for base_code, entry in data.items():
        if not isinstance(entry, dict):
            print(f"ERROR: expected table for '{base_code}'", file=sys.stderr)
            sys.exit(1)

        prefix, cat, num = parse_base_code(base_code)
        brief = entry.get("brief", "")
        group = entry.get("group", "")

        for sev_char, sev_entry in entry.items():
            if sev_char in ("brief", "group"):
                continue
            if sev_char not in SEV_MAP:
                print(f"ERROR: unknown key '{sev_char}' in {base_code}", file=sys.stderr)
                sys.exit(1)
            if not isinstance(sev_entry, dict):
                print(f"ERROR: expected table for '{base_code}.{sev_char}'", file=sys.stderr)
                sys.exit(1)

            full_code = f"{base_code}{sev_char}"
            if full_code in seen:
                print(f"ERROR: duplicate {full_code}", file=sys.stderr)
                sys.exit(1)
            seen.add(full_code)

            explain = textwrap.dedent(sev_entry.get("explain", "")).strip()
            diags.append((full_code, cat, num, SEV_MAP[sev_char], brief, group, explain))

    lines = [
        "///--- The Kairo Project ----------------------------------------------------///",
        "///                                                                          ///",
        "///   Part of the Kairo Project, under the Attribution 4.0 International     ///",
        "///   license (CC BY 4.0).  You are allowed to use, modify, redistribute,    ///",
        "///   and create derivative works, even for commercial purposes, provided    ///",
        "///   that you give appropriate credit, and indicate if changes were made.   ///",
        "///                                                                          ///",
        "///   For more information on the license terms and requirements, please     ///",
        "///     visit: https://creativecommons.org/licenses/by/4.0/                  ///",
        "///                                                                          ///",
        "///   SPDX-License-Identifier: Apache-2.0                                    ///",
        "///   Copyright (c) 2026 The Kairo Project (Apache-2.0)                      ///",
        "///                                                                          ///",
        "///------------------------------------------------------------ KAIRO -------///",
        "",
        "////////////////////////////////////////////////////////////////////////////////",
        "///--------------------------------------------------------------------------///",
        "/// This file is auto-generated by Scripts/gen_diag.py. Do NOT edit manually ///",
        "///--------------------------------------------------------------------------///",
        "////////////////////////////////////////////////////////////////////////////////",
        "",
        "import EvalHash::*;",
        "import Diagnostics::DiagMeta::*;",
        "",
        "enum DiagID derives u32 {",
        "  Invalid = 0,"
    ]
    for code, *_ in diags:
        lines.append(f'  {code} = compute_hash::<r"{code}">(),')
    lines.append("}")
    lines.append("")

    lines.append("eval fn diag_meta(id: DiagID) -> DiagMeta {")
    lines.append("  switch id {")
    lines.append("    case DiagID::Invalid { return DiagMeta{}; }")
    for code, cat, num, sev, brief, group, _ in diags:
        brief_esc = brief.replace('"', '\\"')
        lines.append(f"    case DiagID::{code} {{")
        lines.append(f"      return DiagMeta{{")
        lines.append(f"        category: DiagCategory::{cat},")
        lines.append(f"        severity: DiagSeverity::{sev},")
        lines.append(f"        number: {num},")
        lines.append(f"        hash: static_cast::<u32>(compute_hash::<r\"{code}\">()),")
        lines.append(f'        brief: "{brief_esc}",')
        lines.append(f'        group: "{group}"')
        lines.append(f"      }};")
        lines.append(f"    }}")
    lines.append("  }")
    lines.append("  return DiagMeta{};")
    lines.append("}")
    lines.append("")

    lines.append("eval fn diag_explain(id: DiagID) -> string {")
    lines.append("  switch id {")
    for code, _, _, _, _, _, explain in diags:
        explain_esc = explain.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'").replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t").replace("\0", "\\0").replace("\x0b", "\\v").replace("\x1b", "\\e")
        lines.append(f'    case DiagID::{code} {{ return "{explain_esc}"; }}')
    lines.append("  }")
    lines.append('  return "";')
    lines.append("}")
    lines.append("")

    lines.append("eval fn diag_from_string(code_str: string) -> DiagID {")
    lines.append("  var h = compute_hash(&code_str);")
    lines.append("  return static_cast::<DiagID>(h);")
    lines.append("}")

    lines.append("")
    lines.append("module Diag {")
    for prefix, cat in CAT_MAP.items():
        lines.append(f"  eval fn {prefix}(num: u32, sev: DiagSeverity) -> DiagID {{")
        lines.append(f"    switch sev {{")
        for sev_char, sev_name in SEV_MAP.items():
            full_code = f"{prefix}{num}{sev_char}"
            lines.append(f"      case DiagSeverity::{sev_name} {{")
            # now we need to check the num and match w the appopriate DiagID for this prefix and severity
            lines.append(f"        switch num {{")
            for code, c, n, s, _, _, _ in diags:
                if c == cat and s == sev_name:
                    lines.append(f"          case {n} {{ return DiagID::{code}; }}")
            lines.append(f"          default {{ std::crash(std::Error::RuntimeError(\"invalid diag number for {prefix} and severity {sev_name}\")); }}")
            lines.append(f"        }}")
            lines.append(f"      }}")
        lines.append(f"      default {{ std::crash(std::Error::RuntimeError(\"invalid diag severity\")); }}")
        lines.append(f"    }}")
        lines.append(f"    std::crash(std::Error::RuntimeError(\"reached unreachable code in Diag::{prefix}\"));")
        lines.append(f"    return DiagID::Invalid; // unreachable")
        lines.append(f"  }}")
    lines.append("}")

    print("\n".join(lines))

if __name__ == "__main__":
    main()