#!/usr/bin/env python3
"""
Reads diag.toml, generates DiagRegistry.k (public decls) + TempRegistry.k (impls),
then invokes kairo to compile the impls into an object file.

Usage:
    python3 gen_diag.py <folder with .diag.toml files> --lib-output=<path.o> --output=<Registry.k path>
"""

import sys, tomllib, textwrap, os, subprocess, argparse, hashlib

CAT_MAP = {
    "S": "Syntax", "U": "Uncategorized", "C": "CodeGen",
    "M": "Memory", "R": "Resolution", "L": "Linker",
    "SC": "Semantic", "P": "Portability", "CL": "Lowering",
    "OPT": "Optimization", "I": "Internal"
}
SEV_MAP = {
    "I": "Ignored", "R": "Remark", "V": "Verbose",
    "N": "Note", "D": "Debug", "W": "Warning",
    "E": "Error", "F": "Fatal",
}

def parse_base_code(code: str):
    for prefix in sorted(CAT_MAP.keys(), key=len, reverse=True):
        if code.startswith(prefix):
            num = code[len(prefix):]
            return prefix, CAT_MAP[prefix], int(num)
    raise ValueError(f"bad code: {code}")


def parse_args():
    p = argparse.ArgumentParser(add_help=False)
    p.add_argument("folder")
    p.add_argument("--lib-output", required=True,
                    help="path to the compiled object file, e.g. build/cache/tbldgen.o")
    p.add_argument("--output", required=True,
                    help="path to the public registry file, e.g. Registery.k")
    return p.parse_args()


def load_diags(folder):
    merged_toml = ""
    toml_files = sorted(os.path.join(folder, f) for f in os.listdir(folder) if f.endswith(".diag.toml"))
    for toml_file in toml_files:
        with open(toml_file, "rb") as f:
            merged_toml += f.read().decode("utf-8") + "\n"

    data = tomllib.loads(merged_toml)

    diags = []
    seen = set()

    for base_code, entry in data.items():
        if not isinstance(entry, dict):
            print(f"ERROR: expected table for '{base_code}'", file=sys.stderr)
            sys.exit(1)

        prefix, cat, num = parse_base_code(base_code)
        brief = entry.get("brief", "")
        group = entry.get("group", "")

        for sev_char, sev_entry in entry.items():
            if sev_char in ("brief", "group"):
                continue
            if sev_char not in SEV_MAP:
                print(f"ERROR: unknown key '{sev_char}' in {base_code}", file=sys.stderr)
                sys.exit(1)
            if not isinstance(sev_entry, dict):
                print(f"ERROR: expected table for '{base_code}.{sev_char}'", file=sys.stderr)
                sys.exit(1)

            full_code = f"{base_code}{sev_char}"
            if full_code in seen:
                print(f"ERROR: duplicate {full_code}", file=sys.stderr)
                sys.exit(1)
            seen.add(full_code)

            explain = textwrap.dedent(sev_entry.get("explain", "")).strip()
            diags.append((full_code, cat, num, SEV_MAP[sev_char], brief, group, explain))

    return diags, merged_toml


def license_header():
    return [
        "/// --- The Kairo Project -------------------------------------------------- ///",
        "///",
        "///   Part of the Kairo Project, under the Apache License v2.0 with the",
        "///   Kairo Runtime Library Exception.",
        "///",
        "///   See: https://www.kairolang.org/LICENSE.txt",
        "///   SPDX-License-Identifier: Apache-2.0 WITH KAIRO-RUNTIME-EXCEPTION",
        "///   Copyright (c) 2026 Dhruvan Kartik",
        "///",
        "/// ------------------------------------------------------------------------ ///",
        "",
    ]


def autogen_banner():
    return [
        "////////////////////////////////////////////////////////////////////////////////",
        "///--------------------------------------------------------------------------///",
        "/// This file is auto-generated by Scripts/gen_diag.py. Do NOT edit manually ///",
        "///--------------------------------------------------------------------------///",
        "////////////////////////////////////////////////////////////////////////////////",
        "",
        "#[trivially_import(true)]",
        "",
    ]


def gen_registry(diags):
    """Public interface: enum + fwd decls only, no bodies, not eval."""
    lines = []
    lines += license_header()
    lines += autogen_banner()
    lines += [
        "import Support::EvalHash::*;",
        "import Diagnostic::Meta::*;",
        "",
        "enum DiagID derives u32 {",
        "  Invalid = 0,",
    ]
    for code, *_ in diags:
        lines.append(f'  {code} = compute_hash::<r"{code}">(),')
    lines.append("}")
    lines.append("")

    lines.append("fn diag_meta(id: DiagID) -> DiagMeta;")
    lines.append("fn diag_explain(id: DiagID) -> string;")
    lines.append("fn diag_from_string(code_str: string) -> DiagID;")
    lines.append("")
    lines.append("module Diag {")
    for prefix in CAT_MAP:
        lines.append(f"  fn {prefix}(num: u32, sev: DiagSeverity) -> DiagID;")
    lines.append("}")

    return "\n".join(lines) + "\n"


def gen_temp_registry(diags, registry_module_name):
    """Private impls: full bodies, fns. Compiled into the dylib, never shipped."""
    lines = []
    lines += license_header()
    lines += autogen_banner()
    lines.append(f"import {registry_module_name}::*;")
    lines.append("")

    lines.append("fn diag_meta(id: DiagID) -> DiagMeta {")
    lines.append("  switch id {")
    lines.append("    case DiagID::Invalid { return DiagMeta{}; }")
    for code, cat, num, sev, brief, group, _ in diags:
        brief_esc = brief.replace('"', '\\"')
        lines.append(f"    case DiagID::{code} {{")
        lines.append(f"      return DiagMeta{{")
        lines.append(f'        brief: "{brief_esc}",')
        lines.append(f'        group: "{group}",')
        lines.append(f"        number: {num},")
        lines.append(f"        hash: static_cast::<u32>(compute_hash::<r\"{code}\">()),")
        lines.append(f"        category: DiagCategory::{cat},")
        lines.append(f"        severity: DiagSeverity::{sev}")
        lines.append(f"      }};")
        lines.append(f"    }}")
    lines.append("  }")
    lines.append("  return DiagMeta{};")
    lines.append("}")
    lines.append("")

    lines.append("fn diag_explain(id: DiagID) -> string {")
    lines.append("  switch id {")
    for code, _, _, _, _, _, explain in diags:
        explain_esc = (explain.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'")
                       .replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
                       .replace("\0", "\\0").replace("\x0b", "\\v").replace("\x1b", "\\e"))
        lines.append(f'    case DiagID::{code} {{ return "{explain_esc}"; }}')
    lines.append("  }")
    lines.append('  return "";')
    lines.append("}")
    lines.append("")

    lines.append("fn diag_from_string(code_str: string) -> DiagID {")
    lines.append("  var h = compute_hash(&code_str);")
    lines.append("  return static_cast::<DiagID>(h);")
    lines.append("}")
    lines.append("")

    lines.append("module Diag {")
    for prefix, cat in CAT_MAP.items():
        lines.append(f"  fn {prefix}(num: u32, sev: DiagSeverity) -> DiagID {{")
        lines.append(f"    switch sev {{")
        for sev_char, sev_name in SEV_MAP.items():
            lines.append(f"      case DiagSeverity::{sev_name} {{")
            lines.append(f"        switch num {{")
            for code, c, n, s, _, _, _ in diags:
                if c == cat and s == sev_name:
                    lines.append(f"          case {n} {{ return DiagID::{code}; }}")
            lines.append(f"          default {{ std::crash(std::Error::RuntimeError(\"invalid diag number for {prefix} and severity {sev_name}\")); }}")
            lines.append(f"        }}")
            lines.append(f"      }}")
        lines.append(f"      default {{ std::crash(std::Error::RuntimeError(\"invalid diag severity\")); }}")
        lines.append(f"    }}")
        lines.append(f"    std::crash(std::Error::RuntimeError(\"reached unreachable code in Diag::{prefix}\"));")
        lines.append(f"    return DiagID::Invalid; // unreachable")
        lines.append(f"  }}")
    lines.append("}")

    return "\n".join(lines) + "\n"


def main():
    args = parse_args()

    diags, merged_toml = load_diags(args.folder)
    content_hash = hashlib.sha256(merged_toml.encode("utf-8")).hexdigest()

    output_path = args.output
    lib_output_path = args.lib_output

    output_dir = os.path.dirname(os.path.abspath(output_path)) or "."
    lib_output_dir = os.path.dirname(os.path.abspath(lib_output_path)) or "."
    stamp_file = os.path.join(lib_output_dir, ".gen_diag.hash")

    def read_stamp():
        try:
            with open(stamp_file, "r") as f:
                return f.read().strip()
        except FileNotFoundError:
            return None

    if (read_stamp() == content_hash
            and os.path.exists(output_path)
            and os.path.exists(lib_output_path)):
        return  # nothing changed, exit quietly

    os.makedirs(lib_output_dir, exist_ok=True)

    registry_basename = os.path.splitext(os.path.basename(output_path))[0]
    temp_registry_path = os.path.join(lib_output_dir, f"Temp{os.path.basename(output_path)}")

    # 1. Registery.k -- public interface
    with open(output_path, "w") as f:
        f.write(gen_registry(diags))

    # 2. TempRegistery.k -- private impls, next to --lib-output
    with open(temp_registry_path, "w") as f:
        f.write(gen_temp_registry(diags, registry_basename))

    # 3. compile TempRegistery.k into the object file
    cmd = [
        "kairo", temp_registry_path,
        "-I", output_dir,
        "-I", "Compiler/",
        "--",
        "-o", lib_output_path,
        "-c",
        "-flto=thin",
        "-fuse-ld=lld"
    ]
    if sys.platform == "win32":
        cmd += [
            "-fms-runtime-lib=dll",
            "-DNOMINMAX"
        ]

    print(f"+ {' '.join(cmd)}", file=sys.stderr)
    result = subprocess.run(cmd)
    if result.returncode != 0:
        print(f"ERROR: kairo build failed with exit code {result.returncode}", file=sys.stderr)
        sys.exit(result.returncode)

    with open(stamp_file, "w") as f:
        f.write(content_hash)


if __name__ == "__main__":
    main()